### ISSUE TITLE
Thanks for this great library!

### ISSUE THREAD

**Issue by liangzan** [mr/ftp-client#11]
We were looking high and low for a FTP client and then we found your work. Thanks for the effort!

**Comment by mr** [comment]
No problem! If you find any problems open an issue and I'll try to get to it. The current version on Hackage doesn't throw exceptions for bad responses. So if you try to download a file that doesn't exist it will silently ignore the bad response, and then hang when opening the port for download.

The current master branch fixes this, but the exceptions used are not currently documented and I haven't thoroughly tested it.
