### ISSUE TITLE
0.5.1.0 Release

### ISSUE THREAD

**Issue by dfithian** [mr/ftp-client#13]
Hi, I use ftp-client and ftp-client-conduit and I'm upgrading to LTS-11.16. I noticed you have some commits bumping the package. Any way you can upload a release on Hackage?

**Comment by mr** [comment]
ftp-client is still at 0.5.0.0, and ftp-client-conduit was recently updated to 0.5.0.1. Both are current on Hackage. Can you point to commits you are not seeing?

**Comment by dfithian** [comment]
Oops, just needed to change the extra-deps version of ftp-client-conduit. Thanks!

**Comment by mr** [comment]
I should really look into getting these into stackage. Let me know if you have any other issues.

**Comment by dfithian** [comment]
I've done it before, it's as easy as filing a pull request. Happy to help
you with it if you'd like.
