### ISSUE TITLE
Revise ftp-client to allow for new base, containers, and network

### ISSUE THREAD

**Issue by DanBurton** [mr/ftp-client#16]
One of the joys (read: pains) of `pvp-bounds: both` is that if your resolver is older, it puts restrictive upper bounds on your package. Can you revise the following bounds on hackage?

```diff
30c30
<         network >=2.6.3.6 && <2.7,
---
>         network >=2.6.3.6 && <2.9,
35c35
<         containers >=0.5.11.0 && <0.6
---
>         containers >=0.5.11.0 && <0.7
44c44
<         base >=4.11.1.0 && <4.12
---
>         base >=4.11.1.0 && < 5
```

(The first two in the `library` target, the third in the `test-suite` target.)

**Comment by DanBurton** [comment]
Also, the same revision for `base` on `ftp-client-conduit`'s test suite.

**Comment by mr** [comment]
Makes sense. I've been busy lately, but I'll hopefully get to this soon.

**Comment by DanBurton** [comment]
bump =)

**Comment by DanBurton** [comment]
Bump. If you'd like, I could do it for you if you want to make me a hackage co-maintainer.

**Comment by mr** [comment]
Forgot about this, haha. I'll take care of it now

**Comment by mr** [comment]
Done. Let me know if there are any issues.
