### ISSUE TITLE
network version bounds

### ISSUE THREAD

**Issue by yokodake** [mr/ftp-client#20]
Any reason why the network dependency has an < 2.9 upper bound?
I just tried to build ftp-client with network-3.1.1.1 and it both compiles and passes the tests.

**Comment by DanBurton** [comment]
Bump; I got passing build & tests when run like so (roughly simulating stackage build server):

```bash
stack unpack ftp-client-0.5.1.3 && cd ftp-client-0.5.1.3
# edit ftp-client.cabal, remove constraint on network
echo 'resolver: nightly-2020-04-16' > stack.yaml
stack build --test --bench --no-run-benchmarks --fast
```

So this could be handled by a hackage revision if you like.

**Comment by mr** [comment]
Updated the package. Should be available on hackage now.

**Comment by DanBurton** [comment]
Thank you!

**Comment by yokodake** [comment]
thx
