### ISSUE TITLE
Released package does not accept bytestring v0.11

### ISSUE THREAD

**Issue by ysangkok** [mr/ftp-client#22]
The version 0.5.1.4 on Hackage doesn't accept bytestring version 0.11.

But the source looks like it has no constraint on the version number.

It would be nice if the source and the version on Hackage corresponded. Then one could use ftp-client without tricks like `cabal.project` even though another library demands bytestring version 0.11.

If the trustees added these bounds and you'd like me to ask them to loosen the bounds, please let me know and I will ask.

Thanks for your time, the library is working great for us!

**Comment by ysangkok** [comment]
@mr People on IRC have suggested to me that Stack could have automatically generate these bounds. This issue could be fixed by publishing a new revision, which can be done using the Hackage web interface.

**Comment by sjakobi** [comment]
As a Hackage trustee, I have performed the requested bounds bump as requested in https://github.com/haskell-infra/hackage-trustees/issues/325:

https://hackage.haskell.org/package/ftp-client-0.5.1.4/revisions/

**Comment by ysangkok** [comment]
Closing this since I took over the package.
